#!/usr/bin/env python3.6

"""
BSD 3-Clause License

Copyright (c) 2019, Galym Kerimbekov
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
import panda3d.core as p3d
from panda3d.core import WindowProperties
from direct.showbase.ShowBase import ShowBase
from panda3d.core import TextNode
from pathlib import Path
from Engine.Actors.Player.korlan import Korlan
from Engine.Scenes.scene_one import SceneOne
from Settings.Player.korlan_settings import Player
from Settings.Sound.sound import Sound
from Settings.UI.menu import Menu
from Settings.menu_settings import Graphics

import json
import sys
import configparser
from sys import exit as sys_exit
from os import mkdir
from os.path import isdir, isfile, exists

game_cfg = '{0}/Korlan - Daughter of the Steppes/settings.ini'.format(str(Path.home()))

game_settings = configparser.ConfigParser()
game_settings['Main'] = {'disp_res': '1024x768',
                         'fullscreen': 'off',
                         'antialiasing': 'on',
                         'postprocessing': 'on',
                         'shadows': 'off',
                         'sound': 'on',
                         'music': 'on',
                         'sfx': 'on',
                         'language': 'english',
                         'player': 'Korlan'
                         }

game_settings['Keymap'] = {'forward': 'W',
                           'backward': 'S',
                           'left': 'A',
                           'right': 'D',
                           'crouch': 'C',
                           'jump': 'space',
                           'use': 'E',
                           'attack': 'MOUSE1',
                           'h_attack': 'H',
                           'f_attack': 'F',
                           'block': 'MOUSE2',
                           'sword': '1',
                           'bow': '2',
                           'tengri': '3',
                           'umai': '4'
                           }

game_settings['Debug'] = {}
game_settings['Debug'] = {'set_debug_mode': 'NO',
                          'player_pos_x': '0.0',
                          'player_pos_y': '8.0',
                          'player_pos_z': '-1.09',
                          'player_rot_h': '0.0',
                          'player_rot_p': '0.0',
                          'player_rot_r': '-0.0'
                          }

game_settings.read(game_cfg)
disp_res = game_settings['Main']['disp_res']
disp_res = disp_res.split("x")

p3d.load_prc_file_data(
    '',
    'win-size {0} {1}\n'.format(disp_res[0], disp_res[1])
)

p3d.load_prc_file_data(
    '',
    'window-title Korlan - Daughter of the Steppes\n'
    'show-frame-rate-meter  t\n'
    'audio-library-name p3openal_audio\n'
    'model-cache-dir Cache\n'
    'model-cache-textures t\n'
)


class Main(ShowBase):
    """ Game Parent Directory Path """

    def __init__(self):

        self.cfg_path = None

        self.manualRecenterMouse = None

        self.gfx = Graphics()

        ShowBase.__init__(self)

        self.backfaceCullingOff()
        self.props = WindowProperties()

        self.game_dir = str(Path.cwd())
        self.game_cfg = game_cfg
        self.cfg_warn_text = "# THIS FILE IS AUTOGENERATED. DO NOT EDIT\n\n"
        self.game_cfg_dir = '{}/Korlan - Daughter of the Steppes'.format(str(Path.home()))
        self.game_settings = game_settings
        self.game_settings_filename = 'settings.ini'
        self.cfg_path = {"game_config_path": "{0}/{1}".format(self.game_cfg_dir, self.game_settings_filename)}
        self.game_mode = False
        self.menu_mode = True

        """ Creating same Game Directory"""
        def check_cfg(super):
            if exists('Settings/UI/cfg_path.json'):
                super.cfg_path = json.dumps({'game_config_path': '{0}/{1}'.format(
                    self.game_cfg_dir,
                    self.game_settings_filename),
                    'game_dir': '{0}'.format(self.game_dir)})

                with open('Settings/UI/cfg_path.json', 'w') as f:
                    f.write(str(super.cfg_path))

                if not exists("{0}/{1}".format(self.game_cfg_dir,
                                               self.game_settings_filename)):

                    do_cfg(super)

                    if (isfile('Settings/UI/cfg_path.json') and
                            isfile("{0}/{1}".format(self.game_cfg_dir,
                                                    self.game_settings_filename))):

                        with open('Settings/UI/cfg_path.json', 'w') as f:
                            f.write(str(super.cfg_path))

                        try:
                            self.game_settings.read("{0}/{1}".format(self.game_cfg_dir,
                                                                     self.game_settings_filename))
                            self.player_settings.set_player(self.game_settings['Main']['player'])
                        except configparser.MissingSectionHeaderError:
                            sys_exit("\nFile contains no section headers. I'm bumping file again...")
                            sys_exit("\nFile: {0}/{1}".format(self.game_cfg_dir,
                                                              self.game_settings_filename))

                            force_do_cfg(super)

                else:

                    try:
                        self.game_settings.read("{0}/{1}".format(self.game_cfg_dir, self.game_settings_filename))
                        self.player_settings.set_player(self.game_settings['Main']['player'])
                    except configparser.MissingSectionHeaderError:
                        sys_exit("\nFile contains no section headers. I'm bumping file again...")
                        sys_exit("\nFile: {0}/{1}".format(self.game_cfg_dir, self.game_settings_filename))

                        force_do_cfg(super)

                if isdir(self.game_dir) is False:
                    mkdir(self.game_dir)
                    do_cfg(super)
                    return True
                else:
                    do_cfg(super)
                    return True
            else:
                sys_exit("\nGame data is broken. Please, reinstall it")

        def do_cfg(super):
            if not exists('{0}/{1}'.format(self.game_cfg_dir, self.game_settings_filename)):
                mkdir(self.game_cfg_dir)
                with open('{0}/{1}'.format(self.game_cfg_dir, self.game_settings_filename), 'w') as config_ini:
                    # Turn that setting dict to pass it further
                    config_ini.write(self.cfg_warn_text)
                    self.game_settings.write(config_ini)

        def force_do_cfg(super):
            if not exists('{0}/{1}'.format(self.game_cfg_dir, self.game_settings_filename)):
                mkdir(self.game_cfg_dir)
                with open('{0}/{1}'.format(self.game_cfg_dir, self.game_settings_filename), 'w') as config_ini:
                    # Turn that setting dict to pass it further
                    self.game_settings.write(config_ini)
            else:

                with open('{0}/{1}'.format(self.game_cfg_dir, self.game_settings_filename), 'w') as config_ini:
                    # Turn that setting dict to pass it further
                    self.game_settings.write(config_ini)

        # Notice that you must not call ShowBase.__init__ (or super), the
        # render pipeline does that for you. If this is unconvenient for you,
        # have a look at the other initialization possibilities.

        # Insert the pipeline path to the system path, this is required to be
        # pipeline in a subfolder of your project, you have to adjust this.

        sys.path.insert(0, ".")
        sys.path.insert(0, "RenderPipeline")

        # Import the main render pipeline class
        from rpcore import RenderPipeline
        from rpcore import PointLight

        # Construct and create the pipeline
        self.render_pipeline = RenderPipeline()

        self.game_settings.read("{0}/{1}".format(self.game_cfg_dir, self.game_settings_filename))

        if self.game_settings['Main']['postprocessing'] == 'on':
            self.render_pipeline.pre_showbase_init()
            self.render_pipeline.create(self)

            my_light = PointLight()
            # set desired properties, see below
            self.render_pipeline.add_light(my_light)

        # Game scene loading definitions
        self.scene_one = SceneOne()
        self.korlan = Korlan()
        self.player_settings = Player()
        self.sound = Sound()
        self.text = TextNode("TextNode")

        """ Create game config first! """
        if check_cfg(self):
            self.menu = Menu()
        elif check_cfg(self) and self.game_mode is False:
            self.menu = Menu()
        else:
            sys_exit("\nNo game configuration file created. Please check your game log")

        self.render_type = "menu"
        self.rotateY = 0
        self.rotateX = 0
        self.scene_mode = None

        """ Sounds """
        self.sound.openal_mgr(self, self.game_dir)

        """ Menu """
        if self.menu_mode:
            self.menu.load_main_menu()

    def menu_scene_load(self):
        # Set time of day
        if self.game_settings['Main']['postprocessing'] == 'on':
            self.render_pipeline.daytime_mgr.time = "15:25"

        """ Assets """
        # Test scene
        if self.game_mode is False and self.menu_mode is True:
            self.scene_one.env_load('Assets/Levels/Terrain/Sky.egg',
                                    "MENU_MODE",
                                    "Sky",
                                    [0.0, 10.0, -1.09], [0, 0, 0], [1.25, 1.25, 1.25], 'skybox')

            self.scene_one.asset_load('Assets/Levels/Terrain/Grass.egg',
                                      "MENU_MODE",
                                      "Grass",
                                      [20.0, 10.0, -1.09], [0, 0, 0], [1.25, 1.25, 1.25])

            self.scene_one.asset_load('Assets/Levels/Environment/Nomad house/Nomad_house.egg',
                                      "MENU_MODE",
                                      "Nomad_house",
                                      [1.0, 20.0, -1.09], [65, 0, 0], [1.25, 1.25, 1.25])

            self.scene_one.env_load('Assets/Levels/Terrain/Ground.egg',
                                    "MENU_MODE",
                                    "Ground",
                                    [0.0, 10.0, -1.09], [0, 0, 0], [1.25, 1.25, 1.25], 'ground')

            self.scene_one.env_load('Assets/Levels/Terrain/Mountains.egg',
                                    "MENU_MODE",
                                    "Mountains",
                                    [0.0, 20.0, -1.09], [0, 0, 0], [1.25, 1.25, 1.25], 'mountains')

            self.korlan.set_character("menu",
                                      "Korlan",
                                      self.player_settings.set_player_path(self.game_dir),
                                      "Korlan-Walking.egg")


app = Main()
app.menu_scene_load()

if __name__ == '__main__':
    app.run()
