from setuptools import find_packages, setup

setup(
    name="Korlan",
    version='0.0.1',
    include_package_data=True,
    options={
        'build_apps': {
            'include_patterns': [
                # 'Assets/**/*',
                'Assets/**/tex/*',
                'Configs/Language/*.json',
                'Configs/Keyboard/*.json',
                'Configs/Mice/*.json',
                'Settings/UI/*.json',
                'Settings/UI/ui_tex/**/*.png',
                'Settings/UI/ui_tex/*.png',
                'Settings/UI/**/*.ttf',
                'Settings/UI/**/*.txt',
                'Settings/Sound/*.ogg',
                'Engine/Render/**/*.png',
                'Engine/Render/**/*.jpg',
                'Engine/Render/data/**/**/**/*',
                'Engine/Render/**/*.yaml',
                'Engine/Render/**/*.flag',
                'Engine/Render/**/*.frag.glsl',
                'Engine/Render/**/*.vert.glsl',
                'Engine/Shaders/**/*.frag',
                'Engine/Shaders/**/*.vert',
            ],
            'gui_apps': {
                'Korlan': 'main.py',
            },
            'platforms': [
                'manylinux1_x86_64',
                'win_amd64',
            ],
            'include_modules': {'*': ['Engine.Render.rpcore.native.GPUCommand',
                                      'Engine.Render.rpcore.native.GPUCommandList',
                                      'Engine.Render.rpcore.native.IESDataset',
                                      'Engine.Render.rpcore.native.InternalLightManager',
                                      'Engine.Render.rpcore.native.PointLight',
                                      'Engine.Render.rpcore.native.ShadowManager',
                                      'Engine.Render.rpcore.native.SpotLight',
                                      'Engine.Render.rpcore.native.TagStateManager',
                                      'Engine.Render.rpcore.native.native_',
                                      'Engine.Render.rplibs.yaml.yaml_py3.error',
                                      'cyaml',
                                      'Engine.Render.rplibs.yaml.yaml_py3.dumper',
                                      'Engine.Render.rplibs.yaml.error',
                                      'Engine.Render.rplibs.yaml.yaml_py3.events',
                                      'Engine.Render.rplibs.yaml.yaml_py3.loader',
                                      'Engine.Render.rplibs.yaml.yaml_py3.nodes',
                                      'ordereddict',
                                      'Engine.Render.rpplugins.env_probes.environment_probe',
                                      'Engine.Render.rpplugins.ao',
                                      'thread',
                                      'Engine.Render.rplibs.yaml.yaml_py3.tokens',
                                      'yaml_py2.SafeLoader',
                                      'yaml_py2.YAMLError',
                                      'yaml_py2.load',
                                      'yaml_py3.SafeLoader',
                                      'yaml_py3.YAMLError',
                                      'Engine.Render.rplibs.yaml.yaml_py3.load']},
            'plugins': [
                'pandagl',
                'p3openal_audio',
                'p3ffmpeg',
                'p3ptloader',
            ],
        }
    }
)
