
# Render Pipeline Plugin Configuration
# Instead of editing this file, prefer to use Graphic Settings Menu
# Any formatting and comments will be lost

enabled:
    - ao
    - bloom
    - clouds
    - color_correction
    - scattering
    - sky_ao
    - ssr
    # Here are most heavy postprocessing options
    # - forward_shading
    # - skin_shading
    # - pssm
    # - dof
    # - env_probes
    # - smaa
    # - fxaa
    # - motion_blur
    # - volumetrics
    # - vxgi


overrides:
    ao:
        blur_quality: LOW
        blur_normal_factor: 1.2
        blur_depth_factor: 0.9
        occlusion_strength: 1.6
        clip_length: 2
        technique: SSAO
        ssao_sample_radius: 80.0
        ssao_sequence: halton_3D_8
        ssao_bias: 0.0333
        ssao_max_distance: 6.9
        hbao_sample_radius: 255.0
        hbao_ray_count: 4
        hbao_ray_steps: 3
        hbao_tangent_bias: 0.65
        hbao_max_distance: 11.5
        ssvo_sequence: halton_2D_8
        ssvo_sphere_radius: 18.0
        ssvo_max_distance: 0.82
        alchemy_sample_radius: 210.0
        alchemy_sequence: halton_2D_8
        alchemy_max_distance: 4.75
        ue4ao_sample_radius: 110.5
        ue4ao_sample_sequence: halton_2D_8
        ue4ao_max_distance: 1.87

    bloom:
        num_mipmaps: 8
        bloom_strength: 1.0
        remove_fireflies: False
        lens_dirt_factor: 0.7

    clouds:
        raymarch_steps: 160

    color_correction:
        tonemap_operator: uncharted2
        reinhard_version: rgb
        exponential_factor: 1.0
        uc2t_shoulder_strength: 0.22
        uc2t_linear_strength: 0.3
        uc2t_linear_angle: 0.1
        uc2t_toe_strength: 0.2
        uc2t_toe_numerator: 0.01
        uc2t_toe_denumerator: 0.3
        uc2t_reference_white: 11.2
        vignette_strength: 0.35
        film_grain_strength: 0.125
        color_lut: film_luts/default_lut.png
        use_chromatic_aberration: True
        chromatic_aberration_strength: 0.5
        chromatic_aberration_samples: 2
        manual_camera_parameters: False
        min_exposure_value: 0.01
        max_exposure_value: 1.0
        exposure_scale: 1.0
        brightness_adaption_rate: 3.6
        darkness_adaption_rate: 0.7
        use_sharpen: True
        sharpen_strength: 0.5
        sharpen_twice: False

    dof:
        focal_point: 10.0
        focal_size: 2.5
        blur_strength: 0.5
        near_blur_strength: 0.5

    env_probes:
        probe_resolution: 128
        diffuse_probe_resolution: 2
        max_probes: 16
        max_probes_per_cell: 3

    forward_shading:

    fxaa:
        quality: medium
        subpixel_quality: 0.5
        edge_threshold: 0.166
        min_threshold: 0.833

    motion_blur:
        num_camera_samples: 6
        camera_blur_factor: 0.4
        enable_object_blur: False
        blur_factor: 0.5
        tile_size: 32
        max_blur_radius: 10.0
        num_samples: 12

    pssm:
        max_distance: 100.0
        logarithmic_factor: 2.4
        sun_distance: 100.0
        split_count: 5
        resolution: 1024
        border_bias: 0.058
        use_pcf: True
        filter_sequence: halton_2D_16
        filter_radius: 0.55
        fixed_bias: 0.48
        slope_bias: 0.11
        normal_bias: 0.39
        use_pcss: False
        pcss_sequence: halton_2D_16
        pcss_penumbra_size: 11.0
        pcss_min_penumbra_size: 5.0
        use_distant_shadows: True
        dist_shadow_resolution: 1024
        dist_shadow_clipsize: 1000.0
        dist_shadow_sundist: 500.0
        scene_shadow_resolution: 512
        scene_shadow_sundist: 100.0

    scattering:
        scattering_method: eric_bruneton
        ground_reflectance: 0.1
        rayleigh_factor: 0.5
        rayleigh_height_scale: 8.0
        mie_height_scale: 1.3
        mie_phase_factor: 0.3
        beta_mie_scattering: 4.0
        enable_godrays: False
        atmosphere_start: 100.0

    skin_shading:
        quality: low
        blur_scale: 0.43

    sky_ao:
        sample_radius: 6.0
        max_radius: 200.0
        resolution: 1024
        sample_sequence: poisson_2D_32
        ao_multiplier: 0.25
        ao_bias: 0.3
        blend_factor: 0.05
        capture_height: 250.0

    smaa:
        use_reprojection: True
        smaa_quality: low
        jitter_pattern: halton8
        history_length: 8
        jitter_amount: 0.3

    ssr:
        effect_scale: 1.0
        trace_steps: 64
        history_length: 16
        abort_on_object_infront: True
        intial_bias: 0.1
        hit_tolerance: 0.1
        roughness_fade: 0.72
        skip_invalid_samples: False
        border_fade: 0.005

    volumetrics:
        enable_volumetric_shadows: True
        volumetric_shadow_intensity: 1.0
        volumetric_shadow_brightness: 1.0
        volumetric_shadow_pow: 1.0
        volumetric_max_distance: 150.0
        volumetric_shadow_fadein_distance: 15.0
        volumetric_num_steps: 32

    vxgi:
        grid_resolution: 256
        grid_ws_size: 100.0
        diffuse_cone_steps: 32
        specular_cone_steps: 150

