disabled: [dof, vxgi, fxaa, motion_blur, bloom]
enabled: [ao, color_correction, forward_shading, pssm, scattering, skin_shading, sky_ao,
  smaa, ssr, env_probes, clouds, volumetrics]
overrides:
  ao: {alchemy_max_distance: 5.86, alchemy_sample_radius: 38.86, alchemy_sequence: halton_2D_8,
    blur_depth_factor: 0.88158, blur_normal_factor: 2.97, blur_quality: LOW, clip_length: 10,
    hbao_max_distance: 11.5, hbao_ray_count: 4, hbao_ray_steps: 3, hbao_sample_radius: 255.0,
    hbao_tangent_bias: 0.64997, occlusion_strength: 2.19, ssao_bias: 0.0143, ssao_max_distance: 7.5,
    ssao_sample_radius: 95.29, ssao_sequence: halton_3D_8, ssvo_max_distance: 3.19,
    ssvo_sequence: halton_2D_8, ssvo_sphere_radius: 18.0, technique: SSAO, ue4ao_max_distance: 1.47,
    ue4ao_sample_radius: 50.14286, ue4ao_sample_sequence: halton_2D_8}
  bloom: {bloom_strength: 0.8003, lens_dirt_factor: 0.0, num_mipmaps: 6, remove_fireflies: false}
  clouds: {raymarch_steps: 160}
  color_correction: {brightness_adaption_rate: 3.6, chromatic_aberration_samples: 2,
    chromatic_aberration_strength: 0.019, color_lut: film_luts/default_lut.png, darkness_adaption_rate: 0.7,
    exponential_factor: 1.23, exposure_scale: 1.0, film_grain_strength: 0.1286, manual_camera_parameters: false,
    max_exposure_value: 1.0, min_exposure_value: 0.01, reinhard_version: rgb, sharpen_strength: 0.5,
    sharpen_twice: false, tonemap_operator: optimized, uc2t_linear_angle: 0.1797,
    uc2t_linear_strength: 0.5339, uc2t_reference_white: 10.05, uc2t_shoulder_strength: 0.3352,
    uc2t_toe_denumerator: 0.2787, uc2t_toe_numerator: 0.0029, uc2t_toe_strength: 0.3919,
    use_chromatic_aberration: true, use_sharpen: true, vignette_strength: 0.1286}
  dof: {blur_strength: 0.0, focal_point: 1000.0, focal_size: 994.0, near_blur_strength: 0.4286}
  env_probes: {diffuse_probe_resolution: 2, max_probes: 16, max_probes_per_cell: 3,
    probe_resolution: 128}
  forward_shading: null
  fxaa: {edge_threshold: 0.166, min_threshold: 0.833, quality: low, subpixel_quality: 0.5}
  motion_blur: {blur_factor: 0.5, camera_blur_factor: 0.4, enable_object_blur: false,
    max_blur_radius: 10.0, num_camera_samples: 6, num_samples: 12, tile_size: 32}
  pssm: {border_bias: 0.058, dist_shadow_clipsize: 400.0, dist_shadow_resolution: 4096,
    dist_shadow_sundist: 300.0, filter_radius: 0.7, filter_sequence: halton_2D_32,
    fixed_bias: 0.11429, logarithmic_factor: 3.0, max_distance: 50.0, normal_bias: 0.67,
    pcss_min_penumbra_size: 7.0, pcss_penumbra_size: 2.38, pcss_sequence: halton_2D_16,
    resolution: 1024, scene_shadow_resolution: 512, scene_shadow_sundist: 300.0, slope_bias: 0.0,
    split_count: 4, sun_distance: 100.0, use_distant_shadows: true, use_pcf: true,
    use_pcss: false}
  scattering: {atmosphere_start: 549.61, beta_mie_scattering: 4.0, enable_godrays: false,
    ground_reflectance: 0.1231, mie_height_scale: 1.3, mie_phase_factor: 0.3, rayleigh_factor: 0.5,
    rayleigh_height_scale: 8.0, scattering_method: eric_bruneton}
  skin_shading: {blur_scale: 0.43, quality: medium}
  sky_ao: {ao_bias: 0.0, ao_multiplier: 0.83, blend_factor: 0.01, capture_height: 568.75,
    max_radius: 500.0, resolution: 1024, sample_radius: 17.17, sample_sequence: poisson_2D_32}
  smaa: {history_length: 8, jitter_amount: 0.16143, jitter_pattern: uniform2, smaa_quality: low,
    use_reprojection: true}
  ssr: {abort_on_object_infront: true, border_fade: 0.005, effect_scale: 1.0, history_length: 16,
    hit_tolerance: 0.1, intial_bias: 0.1, roughness_fade: 0.72, skip_invalid_samples: false,
    trace_steps: 64}
  volumetrics: {enable_volumetric_shadows: true, volumetric_max_distance: 79.41429,
    volumetric_num_steps: 128, volumetric_shadow_brightness: 1.66, volumetric_shadow_fadein_distance: 9.49,
    volumetric_shadow_intensity: 8.31, volumetric_shadow_pow: 1.15999}
  vxgi: {diffuse_cone_steps: 32, grid_resolution: 256, grid_ws_size: 100.0, specular_cone_steps: 150}
